; ---------------------------------------------------------------------------
; Object pointers
; ---------------------------------------------------------------------------
                dc.l ObjSonic				; 01
                dc.l Obj02				; 02
                dc.l Obj03				; 03
                dc.l Obj04				; 04
                dc.l Obj05				; 05
                dc.l Obj06				; 06
                dc.l Obj07				; 07
		dc.l NullObject				; 08
                dc.l ObjSonicSpecial			; 09
                dc.l NullObject				; 0A
                dc.l NullObject				; 0B
		dc.l NullObject				; 0C
                dc.l ObjSignpost			; 0D
                dc.l ObjTitleSonic			; 0E
                dc.l ObjTitleText			; 0F
		dc.l ObjAniTest				; 10
                dc.l ObjBridge				; 11
                dc.l ObjSceneryLamp			; 12
                dc.l ObjLavaMaker			; 13
		dc.l ObjLavaball			; 14
                dc.l ObjSwingPtfm			; 15
                dc.l NullObject				; 16
                dc.l ObjSpikeLogs			; 17
		dc.l ObjPlatform			; 18
                dc.l ObjRollingBall			; 19
                dc.l ObjCollapsePtfm			; 1A
                dc.l Obj1B				; 1B
		dc.l ObjScenery				; 1C
                dc.l ObjUnkSwitch			; 1D
                dc.l ObjBallhog				; 1E
                dc.l ObjCrabmeat			; 1F
		dc.l ObjCannonball			; 20
                dc.l ObjHUD				; 21
                dc.l ObjBuzzbomber			; 22
                dc.l ObjBuzzMissile			; 23
		dc.l ObjCannonballExplode		; 24
                dc.l ObjRings				; 25
                dc.l ObjMonitor				; 26
                dc.l ObjExplode				; 27
		dc.l ObjAnimals				; 28
                dc.l ObjPoints				; 29
                dc.l Obj2A				; 2A
                dc.l ObjChopper				; 2B
                dc.l ObjJaws				; 2C
		dc.l ObjBurrobot			; 2D
                dc.l ObjMonitorItem			; 2E
                dc.l ObjMZPlatforms			; 2F
                dc.l ObjGlassBlock			; 30
		dc.l ObjChainPtfm			; 31
                dc.l ObjSwitch				; 32
                dc.l ObjPushBlock			; 33
                dc.l ObjTitleCard			; 34
		dc.l ObjFloorLavaball			; 35
                dc.l ObjSpikes				; 36
                dc.l ObjRingLoss			; 37
                dc.l ObjShield				; 38
		dc.l ObjGameOver			; 39
                dc.l ObjLevelResults			; 3A
                dc.l ObjPurpleRock			; 3B
                dc.l ObjSmashWall			; 3C
		dc.l ObjGHZBoss				; 3D
                dc.l ObjCapsule				; 3E
                dc.l ObjBombExplode			; 3F
                dc.l ObjMotobug				; 40
		dc.l ObjSpring				; 41
                dc.l ObjNewtron				; 42
                dc.l ObjRoller				; 43
                dc.l ObjWall				; 44
                dc.l Obj45				; 45
		dc.l ObjMZBlocks			; 46
                dc.l ObjBumper				; 47
                dc.l ObjGHZBossBall			; 48
                dc.l ObjWaterfallSnd			; 49
		dc.l ObjEntryRingBeta			; 4A
                dc.l Obj4B				; 4B
                dc.l ObjLavafallMalker			; 4C
                dc.l ObjLavafall			; 4D
		dc.l ObjLavaChase			; 4E
                dc.l Obj4F				; 4F
                dc.l ObjYadrin				; 50
                dc.l ObjSmashBlock			; 51
                dc.l ObjMovingPtfm			; 52
		dc.l ObjCollapseFloor			; 53
                dc.l ObjLavaHurt			; 54
                dc.l ObjBasaran				; 55
                dc.l ObjMovingBlocks			; 56
		dc.l ObjSpikedBalls			; 57
                dc.l ObjGiantSpikedBalls		; 58
                dc.l ObjSLZMovingPtfm			; 59
		dc.l ObjCirclePtfm			; 5A
                dc.l ObjStaircasePtfm			; 5B
                dc.l ObjSLZGirder			; 5C
                dc.l ObjFan				; 5D
		dc.l ObjSeeSaw				; 5E

NullObject:
		;bra.w	DeleteObject	; It would be safer to have this instruction here, but instead it just falls through to ObjectFall
